.TH SETENV 1 "January 2026" "hsh" "User Commands"

.SH NAME
setenv \- set an environment variable (hsh builtin)
.SH SYNOPSIS
.B setenv
.I KEY
.I VALUE
.SH DESCRIPTION
The
.B setenv
builtin creates or overwrites the environment variable
.I KEY
with
.I VALUE .
.SH EXIT STATUS
Returns 0 on success and 2 on usage errors or failures.
.SH SEE ALSO
hsh(1)
